## Talking Glossary: Genetic drift (0.75 min)

https://www.genome.gov/genetics-glossary/Genetic-Drift (Links to an external site.)

**Abstract**: "Genetic drift is a mechanism of evolution. It refers to random fluctuations in the frequencies of alleles from generation to generation due to chance events. Genetic drift can cause traits to be dominant or disappear from a population. The effects of genetic drift are most pronounced in small populations."

Audio: https://www.genome.gov/genetics-glossary/Genetic-Drift


**Transcript**: "Genetic drift. I think the best way to look at it is to look at genetic drift as an evolutionary process. It is really the shuffling of our DNA frequency from one generation to the other. And as a result of this chance event, you know, you can emphasize it in things, you know, in the population. So it is in things. Something that may cause a particular type of gene to be more dominant or a particular type disease to disappear from a population. So again, it is a chance event, and it is an evolutionary process."

[Charles N. Rotimi](https://www.genome.gov/staff/Charles-N-Rotimi-PhD), Ph.D.
