## Talking Glossary: Genetic marker 

National Human Genome Research Institute
https://www.genome.gov/genetics-glossary/Genetic-Marker

A genetic marker is a DNA sequence with a known physical location on a chromosome. Genetic markers can help link an inherited disease with the responsible gene. DNA segments close to each other on a chromosome tend to be inherited together. Genetic markers are used to track the inheritance of a nearby gene that has not yet been identified, but whose approximate location is known. The genetic marker itself may be a part of a gene or may have no known function.



Audio: https://www.genome.gov/sites/default/files/tg/en/narration/genetic_marker.mp3

A genetic marker is a landmark. The term "landmark" means a geographic feature that explorers and others would use to find their way back or to an area. I live in Washington, DC. Imagine that you're visiting me, and this is your first time in the U.S. capital, and you really want to visit the White House. But you don't know the city plan, but you have a city guide that says that it is very close by to the Washington Monument. So what do you do? You kind of look up and locate the Washington Monument. And then you start walking through the city blocks, trying to get close to it. Once you get there, you know that you are not in the White House yet, but you know that you are very, very close. So that is what the genetic explorer does.

Belen Hurle, Ph.D.
