## Talking Glossary: Gene Pool (0.75 min)

https://www.genome.gov/genetics-glossary/Gene-Pool (Links to an external site.)

**Abstract**: "A gene pool is the total genetic diversity found within a population or a species. A large gene pool has extensive genetic diversity and is better able to withstand the challenges posed by environmental stresses. Inbreeding contributes to the creation of a small gene pool and makes populations or species more likely to go extinct when faced with some type of stress."

 

Audio: https://www.genome.gov/sites/default/files/tg/en/narration/gene_pool.mp3


**Transcript**: "Gene pool refers to thorough genetic diversity that exists within a population [all of the genetic diversity]. The larger the genetic pool, the more the diversity and the more opportunity this population will have to survive environmental stress that may impact on them. So gene pool is really good in the sense that the larger the gene pool, the more the survival of that particular population in terms of withstanding different things that may come in terms of environment."

[Charles N. Rotimi](https://www.genome.gov/staff/Charles-N-Rotimi-PhD), Ph.D
